# Introduction {#intro}

Structures and data are appropriately complex and specialized in order to ensure rigour and efficiency. 

Some of rogue-book chapter 1 belongs here. Also see spbabel wiki, and discussions in spbabel, spdplyr, babelfish, nf and the gis3d and polygons blog posts. 

The polygons blog post: needs to show another cheating hole, which is to leave out the border colour (as ggplot2 does). This needs a reasonable discusion. 

## Terminology

I often use "object" to refer to an R workspace variable, as well as to a "spatial object" corresponding to a row of "metadata" and the linked geometry it belongs to .. .  need to make this clear throughout. 

Branch, piece/part, object, vertex, coordinate

coordinate, point, vertex - I switch between these at times . . .

object attribute metadata

Spatial also means more than maps in at least the sense that all data are "spatial" beyond the fact that the data were collected at a particular place and time. All data have a "space" in which they exist, and we perform visualization, analysis and modelling in these spaces. This als applies to visualization and model structures, since the "geometries" we use such as histograms, line charts and cluster hulls to name a few can be represented using traditional geo-spatial tools - but often there's a clear disconnect between these worlds. 


## Section on the very general meaning of "space", probably not just a terminology issue

While it's not really part of my goal here, I think it's important to also be clearer on the difference between the topology and the geometry in use. The topology is the scheme by which coordinates are connected in any space and these are dimensional: 0D is a point with no extent, 1D is a line segment connecting two 0D points, and 2D is a planar region - and we can continue up in dimensions. Technically each of these is _primitives_, i.e. a single vertex, a two-vertex line segment, a three-vertex triangle, a four-vertex tetrahedron (and so on) but modern geo-spatial systems usually drop "topology" and represent a planar region as one bounded by a linear path. If we stick with the technical primitives then the topology/geometry distinction is clear: 

* topological dimension is that of the primitives, 0D points, 1D line segment, 2D triangles, 3D tetrahedron, etc.
* geometric dimension is the number of attributes applied to the vertices of a primitive, e.g. \[x,y\] or \[lon,lat,time\] or \[x,y,z,date\] or \[time,lon,temperature,magnitude\]. 

It's important to realize that _spatial_ data has no need to stick to certain conventions, and that the topology of a graph is a certain case of a spatial map. If one axis is time, and the other longitude it's not the business of the data representation to apply these distinctions - that is for the user/researcher. 

List examples where the topology/geometry conflation is made . . .

## Animal tracking data

GIS is a confused place. My perspective is mostly informed by "animal-tracking" data for creatures such as southern elephant seals and short tailed shearwaters. A pretty standard data set is a CSV table of measured location and date-time coordinates for a beast, it might look like this

```
animalID, deploymentID, longitude, latitude, datetime, measure_class
#...
```

Is this tidy data? Does this fit standard structures for data.  

The tidy data definition [from tidyr vignette](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html). 

>  A variable contains all values that measure the same underlying attribute (like height, temperature, duration) 
> across units. An observation contains all values measured on the same unit (like a person, or a day, or a race) across 
> attributes.

Our data is pretty tidy, each row tells us information about a tag location measurement, we know the individual animal, the deployment (we have to put the tag on, and retrieve it), and we know a longitude, latitude and date time. Those last three measures are discrete samples from a continuous process, i.e. the animal moving around. We ignore the 3rd spatial dimension for now. What we have is three continuous "spatial" measures and grouping attributes to describe two levels. 



What does this data look like in a plot? 

```R
ggplot() + aes(x = longitude, y = latitude, group = deploymentID, col = ID) + geom_point()

```


Is this **spatial**?  Let's have a look at the OGC zoo, we have POINT, MULTIPOINT, LINESTRING, POLYGON, MULTILINESTRING, MULTIPOLYGON, GEOMETRYCOLLECTION, CIRCULARSTRING, COMPOUNDCURVE, MULTICURVE, MULTISURFACE, CURVE, SURFACE, POLYHEDRALSUFACE, TIN, TRIANGLE, EMPTY. 

The candidates that seem sensible are POINT, MULTIPOINT, LINESTRING, MULTILINESTRING. How do they fare for representing our data. 


