# The GIS contract

GIS provides a table-based front-end where there is a one-to-one relationship between a geometric object, and a row in a table that contains attribute metadata about that object. I call this the "GIS contract", and you can see this in the linked selections (brushing) in QGIS, Manifold and other systems. 

## The **sp** package

Spatial classes, formal inheritance, heirarchical objects. 

The Spatial classes provided by the sp package are very widely used because they provide the formal guarantee of the GIS contract, and use this for a systematic coupling with other tools: 

* the huge number of formats provided by GDAL input/output
* powerful high-level methods for visualization, manipulation, analysis and modelling
* 

The DataFrame is the basic unit in _sp_, but it's not *actually* a data frame - every single data frame -like behaviour is provided indirectly by methods. This works very well, in that the object behaves like a data frame with "[" and has dim, nrows, and "$" ... but the disconnect between this and the underlying geometric details eventually becomes a limitation. Users routinely reach under the hood to get at the details with "@" ...


The attribute metadata are discrete but the geometry is continuous - this an important point, relate to the space-is-general discussion. Spatial topology ties the geometry together, and database topology ties the system together.  

## The **ggplot2** package

Data frames are the fundamental unit for **ggplot2**, but for spatial data the first step is to decompose the hierarchical complexity of a Spatial object to a single data frame. 

This breaks the "GIS contract", since the individual objects are now spread over multiple rows of the table of coordinates. 

## Connections

ggplot2 lets you reach under the abstractly, in that you can specify aesthetics and topology generally, you assign the x, y, the lower-grouping ID (for parts within objects), and the grouping ID (for objects) for the definitions of what the objects are and the attributes used. This is extremely powerful, but not generally used. 

ggplot2 examples

Example of a perspective plot in ggplot2 using transformation? Or another 3rd geometry attribute . . .

Ability to drop holes (though limitations of mult-hole anyway)

This flexibility is what  a lot of users want, but sp *really* makes it hard. 


## Pros and cons

Ability to user-choose attributes from the data - independence of analysis from the visualization


## Relations and the difference between sp and ggplot2 forms

There's a difficulty for non-experts to deal with relational data, there's a level of abstraction in the process that provides confusion. We see this in many fields, where a single table is the basic unit of analysis and the lessons of database normalization are nowhere to be seen. A common example is animal tracking data, which at the minimum stores a trip (or burst or group) ID, x, y, date-time, and may include individual or tag ID (object). Technically, these data should have a metadata table with observations about the tag deployment (date, location, recovery, animal departure/return date), an individual table with observations on the animal species, and the table of coordinates of the actual tag space-time measurements. 

This is a well- recognized problem, especially in collaborative studies where the entire data set is stored in a single CSV ... [probably less ranting here,] but the relational table example is a good one. 

A key definition here is the idea of a structural index (the row or column number in a table or array) versus a relational index where the value of a key is used to match records. The relational index can be transferred from one data set to another by subsetting and appending, and survive resorting generally - but the structural index cannot - it must either be maintained in its position or be updated when the overal dataset is subsetted, or changed. 

Recurisve objects like lists in R stand in place of both structurual and relational indexes, the structure of the list is an implicit marker of the index - though it might also store a particular label. 



